// WARNING !!! Classnames must all be uppercase for search functions to work!

OPCB_econ_TierList_ENG = [

	//TIER 1
	[
	"RHSUSF_M1A2SEP2D_USARMY",
	"RHSUSF_M109D_USARMY",
	"B_MBT_01_ARTY_F",
	"B_MBT_01_TUSK_F"
	],

	//TIER 2
	[
	"RHSUSF_M1A1AIMD_USARMY",
	"I_MBT_03_CANNON_F",
	"B_AFV_WHEELED_01_UP_CANNON_F"
	],

	//TIER 3
	[
	"RHS_M6",
	"RHS_BMD4MA_VDV",
	"B_AFV_WHEELED_01_CANNON_F"
	],

	//TIER 4
	[
	"RHS_M2A3_BUSKIII",
	"I_APC_WHEELED_03_CANNON_F",
	"RHSUSF_STRYKER_M1134_D",
	//"RHS_BMD2M",
	"B_APC_WHEELED_01_CANNON_F"
	],

	//TIER 5
	[
	"B_APC_TRACKED_01_AA_F",
	"I_APC_TRACKED_03_CANNON_F",
	//"RHS_BMD1P",
	"RHS_M2A2_BUSKI"
	],

	//TIER 6
	[
	"RHSUSF_STRYKER_M1132_M2_D",
	"I_LT_01_CANNON_F",
	"I_LT_01_AT_F"
	],

	//TIER 7
	[
	"RHSUSF_STRYKER_M1126_M2_D",
	"RHSUSF_STRYKER_M1126_MK19_D",
	"I_LT_01_AA_F"
	//"UK3CB_CW_US_B_EARLY_M60A1"
	],

	//TIER 8
	[
	"B_APC_TRACKED_01_RCWS_F",
	"RHSUSF_M113D_USARMY",
	"RHSUSF_M113D_USARMY_MK19"
	],

	//TIER 9
	[
	"RHSUSF_M113D_USARMY_M240",
	"RHSGREF_CDF_B_ZSU234",
	//"LOP_IRAN_BTR80",
	"RHSUSF_M1117_D",
	"RHSUSF_M113D_USARMY_SUPPLY"
	//"UK3CB_B_LAV25_US_WDL"
	],

	//TIER 10
	[
	"I_LT_01_SCOUT_F",
	"RHSUSF_M113D_USARMY_UNARMED",
	"RHSUSF_M113D_USARMY_MEDICAL"
	]

];