// WARNING !!! Classnames must all be uppercase for search functions to work!

OPCB_econ_vehicleAirAttackTypes = [
	"RHS_UH60M_ESSS_D",
	"RHS_MELB_AH6M",
	"I_HELI_LIGHT_03_DYNAMICLOADOUT_F",
	"RHS_UH1Y_D",
	"B_PLANE_FIGHTER_01_F",
	"B_PLANE_CAS_01_DYNAMICLOADOUT_F",
	"B_HELI_ATTACK_01_DYNAMICLOADOUT_F",
	"RHS_AH1Z",
	"RHS_A10",
	"RHS_AH64D",
	"I_PLANE_FIGHTER_04_F",
	"O_HELI_LIGHT_02_DYNAMICLOADOUT_F",
	"B_UAV_02_DYNAMICLOADOUT_F",
	"RHS_L39_CDF_B_CDF",
	"RHS_L159_CDF_B_CDF",
	"RHSGREF_CDF_B_SU25",
	"RHS_C130J",
	"RHSSAF_AIRFORCE_L_18",
	"RHS_MI24P_VDV",
	"O_PLANE_CAS_02_DYNAMICLOADOUT_F",
	"RHS_L39_CDF",
	"FIR_F15E",
	"FIR_A10C"
];

OPCB_econ_vehicleGroundAttackTypes = [
	"B_MBT_01_TUSK_F",
	"B_MBT_01_CANNON_F",
	"RHSUSF_M1A1AIMD_USARMY",
	"RHSUSF_M1A2SEP1TUSKIID_USARMY",
	"I_MBT_03_CANNON_F",
	"RHSUSF_M1A1AIM_TUSKI_D",
	"RHSUSF_M1A2SEP1D_USARMY",
	"RHSUSF_M1A2SEP1TUSKID_USARMY",
	"B_MBT_01_ARTY_F",
	"RHSUSF_M109D_USARMY",
	"RHS_T72BB_TV",
	"RHSUSF_M142_USARMY_D",
	"B_AFV_WHEELED_01_UP_CANNON_F",
	"B_AFV_WHEELED_01_CANNON_F",
	"RHSUSF_M1A2SEP2D_USARMY"
];

OPCB_econ_vehicleGroundApcTypes = [
	"B_APC_TRACKED_01_AA_F",
	"RHS_BMP2D_MSV",
	"O_APC_WHEELED_02_RCWS_F",
	"I_LT_01_AA_F",
	"I_LT_01_CANNON_F",
	"RHS_BMD4MA_VDV",
	"RHS_M2A3_BUSKIII",
	"RHS_M2A2_BUSKI",
	"RHS_M6",
	"I_APC_WHEELED_03_CANNON_F",
	"RHSUSF_STRYKER_M1134_D",
	"B_APC_TRACKED_01_RCWS_F",
	"B_APC_WHEELED_01_CANNON_F",
	"I_APC_TRACKED_03_CANNON_F",
	"O_T_APC_TRACKED_02_CANNON_GHEX_F",
	"UK3CB_B_LAV25_US_WDL",
	"UK3CB_CW_US_B_LATE_AAV"
];
