mehlandTieredUnits = createHashMap;
mehlandInfantryTiers = createHashMapFromArray [
	[
		1,
		[
			"I_L_Hunter_F",
			"I_L_Looter_Rifle_F",
			"I_L_Looter_SG_F",
			"I_L_Criminal_SG_F",
			"I_L_Looter_SMG_F"	
		]
		
	],
	[
		2,
		[			
			"I_L_Hunter_F",
			"I_L_Looter_Rifle_F",
			"I_L_Looter_SG_F",
			"I_L_Criminal_SG_F",
			"I_L_Looter_SMG_F",
			"UK3CB_LNM_I_TL",
			"UK3CB_LNM_I_SEN_1",
			"UK3CB_LNM_I_SEN_3",
			"UK3CB_LNM_I_SEN_2",
			"UK3CB_LNM_I_SEN_4",
			"UK3CB_LNM_I_SL",
			"UK3CB_LNM_I_RIF_2",
			"UK3CB_LNM_I_RIF_1",
			"UK3CB_LNM_I_OFF",
			"UK3CB_LNM_I_MD",
			"UK3CB_LNM_I_MK",
			"UK3CB_LNM_I_MG",
			"UK3CB_LNM_I_LMG",
			"UK3CB_LNM_I_LAT",
			"UK3CB_LNM_I_GL",
			"UK3CB_LNM_I_ENG",
			"UK3CB_LNM_I_DEM",
			"UK3CB_LNM_I_COM",
			"UK3CB_LNM_I_AR",
			"UK3CB_LNM_I_AT"
		]
	],
	[
		3,
		[
			"UK3CB_LNM_I_TL",
			"UK3CB_LNM_I_SEN_1",
			"UK3CB_LNM_I_SEN_3",
			"UK3CB_LNM_I_SEN_2",
			"UK3CB_LNM_I_SEN_4",
			"UK3CB_LNM_I_SL",
			"UK3CB_LNM_I_RIF_2",
			"UK3CB_LNM_I_RIF_1",
			"UK3CB_LNM_I_OFF",
			"UK3CB_LNM_I_MD",
			"UK3CB_LNM_I_MK",
			"UK3CB_LNM_I_MG",
			"UK3CB_LNM_I_LMG",
			"UK3CB_LNM_I_LAT",
			"UK3CB_LNM_I_GL",
			"UK3CB_LNM_I_ENG",
			"UK3CB_LNM_I_DEM",
			"UK3CB_LNM_I_COM",
			"UK3CB_LNM_I_AR",
			"UK3CB_LNM_I_AT"
		]
	],
	[
		4,
		[
			"UK3CB_LNM_I_TL",
			"UK3CB_LNM_I_SEN_1",
			"UK3CB_LNM_I_SEN_3",
			"UK3CB_LNM_I_SEN_2",
			"UK3CB_LNM_I_SEN_4",
			"UK3CB_LNM_I_SL",
			"UK3CB_LNM_I_RIF_2",
			"UK3CB_LNM_I_RIF_1",
			"UK3CB_LNM_I_OFF",
			"UK3CB_LNM_I_MD",
			"UK3CB_LNM_I_MK",
			"UK3CB_LNM_I_MG",
			"UK3CB_LNM_I_LMG",
			"UK3CB_LNM_I_LAT",
			"UK3CB_LNM_I_GL",
			"UK3CB_LNM_I_ENG",
			"UK3CB_LNM_I_DEM",
			"UK3CB_LNM_I_COM",
			"UK3CB_LNM_I_AR",
			"UK3CB_LNM_I_AT",
			"UK3CB_LNM_I_SF_TL",
			"UK3CB_LNM_I_SF_SL",
			"UK3CB_LNM_I_SF_RIF_2",
			"UK3CB_LNM_I_SF_RIF_1",
			"UK3CB_LNM_I_SF_MD",
			"UK3CB_LNM_I_SF_MK",
			"UK3CB_LNM_I_SF_MG",
			"UK3CB_LNM_I_SF_LMG",
			"UK3CB_LNM_I_SF_LAT",
			"UK3CB_LNM_I_SF_GL",
			"UK3CB_LNM_I_SF_ENG",
			"UK3CB_LNM_I_SF_DEM",
			"UK3CB_LNM_I_SF_AR",
			"UK3CB_LNM_I_SF_AT"
		]
	],
	[
		5,
		[
			"UK3CB_LNM_I_SF_TL",
			"UK3CB_LNM_I_SF_SL",
			"UK3CB_LNM_I_SF_RIF_2",
			"UK3CB_LNM_I_SF_RIF_1",
			"UK3CB_LNM_I_SF_MD",
			"UK3CB_LNM_I_SF_MK",
			"UK3CB_LNM_I_SF_MG",
			"UK3CB_LNM_I_SF_LMG",
			"UK3CB_LNM_I_SF_LAT",
			"UK3CB_LNM_I_SF_GL",
			"UK3CB_LNM_I_SF_ENG",
			"UK3CB_LNM_I_SF_DEM",
			"UK3CB_LNM_I_SF_AR",
			"UK3CB_LNM_I_SF_AT"
		]
	],
	[
		6,
		[
			"UK3CB_LDF_I_TL",
			"UK3CB_LDF_I_SL",
			"UK3CB_LDF_I_RIF_1",
			"UK3CB_LDF_I_RIF_2",
			"UK3CB_LDF_I_MK",
			"UK3CB_LDF_I_MG",
			"UK3CB_LDF_I_LAT",
			"UK3CB_LDF_I_JNR_OFF",
			"UK3CB_LDF_I_GL",
			"UK3CB_LDF_I_ENG",
			"UK3CB_LDF_I_AR",
			"UK3CB_LDF_I_AT",
			"UK3CB_LDF_I_MD"
		]
	],
	[
		7,
		[
			"UK3CB_LDF_I_SF_TL",
			"UK3CB_LDF_I_SF_SPOT",
			"UK3CB_LDF_I_SF_SNI",
			"UK3CB_LDF_I_SF_SL",
			"UK3CB_LDF_I_SF_RIF_2",
			"UK3CB_LDF_I_SF_RIF_1",
			"UK3CB_LDF_I_SF_MD",
			"UK3CB_LDF_I_SF_MK",
			"UK3CB_LDF_I_SF_MG",
			"UK3CB_LDF_I_SF_LAT",
			"UK3CB_LDF_I_SF_GL",
			"UK3CB_LDF_I_SF_ENG",
			"UK3CB_LDF_I_SF_DEM",
			"UK3CB_LDF_I_SF_AR",
			"UK3CB_LDF_I_SF_AT"
		]
	],
	[
		8,
		[
			"UK3CB_ION_I_Woodland_TL",
			"UK3CB_ION_I_Woodland_SL",
			"UK3CB_ION_I_Woodland_SPOT",
			"UK3CB_ION_I_Woodland_SNI",
			"UK3CB_ION_I_Woodland_RIF_1",
			"UK3CB_ION_I_Woodland_RIF_2",
			"UK3CB_ION_I_Woodland_MD",
			"UK3CB_ION_I_Woodland_MK",
			"UK3CB_ION_I_Woodland_MG",
			"UK3CB_ION_I_Woodland_LAT",
			"UK3CB_ION_I_Woodland_GL",
			"UK3CB_ION_I_Woodland_ENG",
			"UK3CB_ION_I_Woodland_ENG",
			"UK3CB_ION_I_Woodland_DEM",
			"UK3CB_ION_I_Woodland_AR",
			"UK3CB_ION_I_Woodland_AT"
		]
	],
	[
		9,
		[
			"UK3CB_ION_I_Woodland_SF_TL",
			"UK3CB_ION_I_Woodland_SF_SNI",
			"UK3CB_ION_I_Woodland_SF_SPOT",
			"UK3CB_ION_I_Woodland_SF_SL",
			"UK3CB_ION_I_Woodland_SF_RIF_1",
			"UK3CB_ION_I_Woodland_SF_RIF_2",
			"UK3CB_ION_I_Woodland_SF_RIF_4",
			"UK3CB_ION_I_Woodland_SF_RIF_3",
			"UK3CB_ION_I_Woodland_SF_MD",
			"UK3CB_ION_I_Woodland_SF_MK",
			"UK3CB_ION_I_Woodland_SF_MG",
			"UK3CB_ION_I_Woodland_SF_LAT",
			"UK3CB_ION_I_Woodland_SF_GL",
			"UK3CB_ION_I_Woodland_SF_ENG",
			"UK3CB_ION_I_Woodland_SF_DEM",
			"UK3CB_ION_I_Woodland_SF_AT"
		]
	]
];

mehlandVehicleCrewTiers = createHashMapFromArray [[1,"UK3CB_LNM_I_SF_RIF_1"], [2,"UK3CB_LDF_I_RIF_1"]];
mehlandStaticCrewTiers = createHashMapFromArray [[1,"UK3CB_LNM_I_SF_RIF_1"], [2,"UK3CB_LDF_I_RIF_1"]];

mehlandVehicleTiers = createHashMapFromArray [
	[
		1,
		[
			"UK3CB_LNM_I_BTR40_MG",
			"UK3CB_LNM_I_BRDM2",
			"UK3CB_LNM_I_Hilux_Dshkm",
			"UK3CB_LNM_I_Hilux_Metis",
			"UK3CB_LNM_I_LR_M2",
			"UK3CB_LNM_I_LR_SF_M2",
			"UK3CB_LNM_I_Offroad_M2",
			"UK3CB_LNM_I_Pickup_DSHKM",
			"UK3CB_LNM_I_Pickup_SPG9",
			"UK3CB_LNM_I_Hilux_Pkm",
			"UK3CB_LNM_I_LR_Open",
			"UK3CB_LNM_I_LR_Closed",
			"UK3CB_LNM_I_Ural_Open",
			"UK3CB_LNM_I_Van_Transport",
			"UK3CB_LDF_I_Mi8AMTSh",
			"UK3CB_LDF_I_Mi8",
			"UK3CB_LDF_I_Mi_24V",
			"UK3CB_LNM_I_T55",
			"UK3CB_LNM_I_T72A",
			"UK3CB_LNM_I_T72B",
			"UK3CB_LNM_I_Hilux_Open"
		]

	],
	[
		2,
		[
			"UK3CB_LDF_I_Tigr_STS",
			"UK3CB_LDF_I_Tigr_FFV",
			"UK3CB_LDF_I_M1025_M2",
			"UK3CB_LDF_I_M1025_TOW",
			"UK3CB_LDF_I_M1151_GPK_M2",
			"UK3CB_LDF_I_M1151_GPK_PKM",
			"UK3CB_LDF_I_M1151_OGPK_M2",
			"UK3CB_LDF_I_M998_2DR",
			"UK3CB_LDF_I_T810_Closed_PKM",
			"UK3CB_LDF_I_Marshall",
			"UK3CB_LDF_I_Marshall_Cage",
			"UK3CB_LDF_I_Marshall_Camo",
			"UK3CB_LDF_I_Offroad",
			"UK3CB_LDF_I_Offroad_M2",
			"UK3CB_LDF_I_Offroad_AT",
			"UK3CB_LDF_I_Pickup",
			"UK3CB_LDF_I_Pickup_M2",
			"UK3CB_LDF_I_Pickup_SPG9",
			"UK3CB_LDF_I_Leopard",
			"UK3CB_ION_I_Woodland_MELB_AH6M",
			"UK3CB_ION_I_Woodland_Bell412_Utility",
			"UK3CB_ION_I_Woodland_Bell412_Armed",
			"UK3CB_ION_I_Woodland_Merlin",
			"UK3CB_ION_I_Woodland_MELB_MH6M",
			"UK3CB_ION_I_Woodland_Orca",
			"UK3CB_ION_I_Woodland_Orca_Armed_MULTI",
			"UK3CB_ION_I_Woodland_UH1H_M240",
			"UK3CB_ION_I_Woodland_UH1H_GUNSHIP",
			"UK3CB_ION_I_Woodland_UH1H",
			"UK3CB_LDF_I_ZsuTank",
			"UK3CB_LDF_I_T810_ZU23",
			"UK3CB_LDF_I_Mi_24G",
			"UK3CB_LDF_I_Mi_24G_UPK23",
			"UK3CB_LDF_I_Mi8AMTSh",
			"UK3CB_LDF_I_Mi8"
		]

	]
];

mehlandTieredUnits set ["world_name", "mehland"];
mehlandTieredUnits set ["infantry_tiers", mehlandInfantryTiers];
mehlandTieredUnits set ["vehicle_crew_tiers", mehlandVehicleCrewTiers];
mehlandTieredUnits set ["static_crew_tiers", mehlandStaticCrewTiers];
mehlandTieredUnits set ["vehicle_tiers", mehlandVehicleTiers];

tieredUnits set ["mehland", mehlandTieredUnits];
